package com.thinkworks.techecosystem.enums;

public enum EntityType {
    DEVELOPER,
    TESTER,
    MANAGER,
    DEVOPS,
    INTERN,
    DESIGNER,
    DATA_ENGINEER,
    AI_ENGINEER,
    SECURITY_ENGINEER,
    CLOUD_ENGINEER,
    SUPPORT_ENGINEER,
    HR,
    RECRUITER,
    PRODUCT_MANAGER,
    BUSINESS_ANALYST,
    SYSTEM_ADMIN,
    NETWORK_ENGINEER,
    QA_ENGINEER,
    AUTOMATION_ENGINEER,
    MOBILE_DEVELOPER,
    BACKEND_DEVELOPER,
    FRONTEND_DEVELOPER,
    FULL_STACK_DEVELOPER,
    TECHNICAL_WRITER,
    CONSULTANT,


    GAME_DEVELOPER,
    BLOCKCHAIN_ENGINEER,
    DATA_SCIENTIST,
    ML_TESTER,
    UX_RESEARCHER


}
